import Navbar from "@/components/Home/Navbar"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html dir="rtl" lang="ar">
      <body>
        <Navbar/>
        {children}</body>
    </html>
  )
}
